pipeline {
    agent none

    triggers {
        cron('H */11 * * *')
    }
    
    stages {
        stage('Run on All Nodes') {
            matrix {
                axes {
                    axis {
                        name 'NODE'
                        values 'dns1', 'dns2', 'vpn1', 'jenkins1'
                    }
                }
                agent {
                    node "${NODE}"
                }
                stages {
                    stage('Checkout') {
                        steps {
                            checkout scm
                        }
                    }
                    
                    stage('Update Linux Distribution') {
                        steps {
                            script {
                                echo "Node Execution: ${env.NODE_NAME}"
                                
                                sh 'dnf update -y'
                                
                            }
                        }
                    }

                    stage('Cleanup After') {
                        steps {
                            cleanWs()
                        }
                    }
                }
            }
        }
    }
}
